import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navbar from "./components/Navbar";
import ProviderApp from "./Redux/Store/ProviderApp";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ToDo-LIST",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <link rel="shortcut icon" href="/task-list.png" />
      <body className="denim">

        <ProviderApp>
        <Navbar/>

        {children}
        </ProviderApp>
        
        </body>
    </html>
  );
}
